version: '2'

# The HOST listener is for connecting to the cluster from the host machine running Docker
# The EXTERNAL listener is for connecting to the cluster from a network. Change the EXTERNAL listener IP to the IP of the host machine on the desired network.

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper-local
    ports:
      - '2181:2181'
    networks:
      - kafka
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.4.0-debian-11-r21'
    container_name: kafka-local
    ports:
      - '9093:9093'
      - '9094:9094'
    networks:
      - kafka
    volumes:
      - ./ssl/server/certs:/bitnami/kafka/config/certs
      - ./kafka_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=CLIENT://0.0.0.0:9092,SASL_SSL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,SASL_SSL://host.docker.internal:9093,EXTERNAL://192.168.1.136:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,SASL_SSL:SASL_SSL,EXTERNAL:PLAINTEXT
      
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=server-truststore-pass
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=server-keystore-pass
      - KAFKA_CFG_SSL_KEY_PASSWORD=server-keystore-pass
      - KAFKA_CFG_SSL_CLIENT_AUTH=required

      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT
    depends_on:
      - zookeeper
networks:
  kafka:
    name: kafka-network